pre-commit:
  parallel: false
  jobs:
    - name: lint
      run: pnpm dlx eslint --fix {staged_files}
      stage_fixed: true
    - name: fmt
      run: pnpm dlx prettier --write {staged_files}
      stage_fixed: true
